### ISSUE TITLE
ERROR SyntaxError: Invalid JS code

### ISSUE THREAD

**Issue by sonnyp** [hubot-scripts/hubot-google-translate#17]
When requesting `Hamilton, translate me hola`

```
[Sat Nov 30 2019 16:07:19 GMT+0100 (Central European Standard Time)] ERROR SyntaxError: Invalid JS code
  at /home/sonny/Projects/hamilton/node_modules/hubot-google-translate/src/google-translate.coffee:122:23, <js>:131:19
  at IncomingMessage.<anonymous> (/home/sonny/Projects/hamilton/node_modules/scoped-http-client/src/index.js:95:22)
  at IncomingMessage.emit (events.js:215:7)
  at endReadableNT (_stream_readable.js:1183:12)
  at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

First I thought it was an issue with my setup but other CoffeeScript scripts work fine like https://github.com/hubot-scripts/hubot-pugme

```
  "dependencies": {
    "hubot": "^3.3.2",
    "hubot-diagnostics": "^1.0.0",
    "hubot-google-images": "^0.2.7",
    "hubot-google-translate": "^0.2.1",
    "hubot-help": "^1.0.1",
    "hubot-heroku-keepalive": "^1.0.3",
    "hubot-maps": "0.0.3",
    "hubot-pugme": "^0.1.1",
    "hubot-redis-brain": "^1.0.0",
    "hubot-rules": "^1.0.0",
    "hubot-scripts": "^2.17.2",
    "hubot-shipit": "^0.2.1",
    "hubot-xmpp": "git+https://git@github.com/xmppjs/hubot-xmpp.git"
  },
```

```
[sonny@evoli]~/Projects/hamilton% node -v
v12.13.0
[sonny@evoli]~/Projects/hamilton% npm -v
6.12.0

```

**Comment by sonnyp** [comment]
I used `npx -p yo -p generator-hubot -c 'yo hubot --adapter=xmpp'` to scaffold the bot.
