### ISSUE TITLE
Google Responds with a 302

### ISSUE THREAD

**Issue by edc1591** [hubot-scripts/hubot-google-translate#5]
This seems to be broken again. I logged out the response body and am getting this:

    2015-06-18T17:58:25.364331+00:00 app[slack.1]: <A HREF="https://ipv4.google.com/sorry/IndexRedirect?continue=https://translate.google.com/translate_a/single%3Fclient%3Dt%26hl%3Den%26sl%3Dauto%26ssel%3D0%26tl%3Den%26tsel%3D0%26q%3D%2522hola%2522%26ie%3DUTF-8%26oe%3DUTF-8%26otf%3D1%26dt%3Dbd%26dt%3Dex%26dt%3Dld%26dt%3Dmd%26dt%3Dqca%26dt%3Drw%26dt%3Drm%26dt%3Dss%26dt%3Dt%26dt%3Dat&amp;q=CGMSBBcW29MYwI2MrAUiGQDxp4NLJ08FWHvubHK_CTXVBOn04gT7WAc">here</A>.
    2015-06-18T17:58:25.364334+00:00 app[slack.1]:
    2015-06-18T17:58:25.364328+00:00 app[slack.1]: The document has moved
    2015-06-18T17:58:25.366566+00:00 app[slack.1]:   at /app/scripts/translate.coffee:132:19
    2015-06-18T17:58:25.366571+00:00 app[slack.1]:   at _stream_readable.js:908:16
    2015-06-18T17:58:25.364321+00:00 app[slack.1]: <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
    2015-06-18T17:58:25.366568+00:00 app[slack.1]:   at IncomingMessage.<anonymous> (/app/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
    2015-06-18T17:58:25.364327+00:00 app[slack.1]: <H1>302 Moved</H1>
    2015-06-18T17:58:25.366570+00:00 app[slack.1]:   at IncomingMessage.emit (events.js:129:20)
    2015-06-18T17:58:25.364325+00:00 app[slack.1]: <TITLE>302 Moved</TITLE></HEAD><BODY>
    2015-06-18T17:58:25.364332+00:00 app[slack.1]: </BODY></HTML>
    2015-06-18T17:58:25.366564+00:00 app[slack.1]: [Thu Jun 18 2015 13:58:25 GMT-0400 (EDT)] ERROR SyntaxError: Invalid JS code
    2015-06-18T17:58:25.366573+00:00 app[slack.1]:   at process._tickDomainCallback (node.js:381:11)

**Comment by technicalpickles** [comment]
Relevant code: https://github.com/hubot-scripts/hubot-google-translate/blob/master/src/google-translate.coffee#L89-L102

**Comment by ericjsilva** [comment]
This isn't a bug. This is caused by Google detecting a number of requests coming from an automated service that violates the Terms of Service.

I assume they are trying to get everyone to use the paid Translation Service API.

**Comment by technicalpickles** [comment]
If that's the case, I wonder if they return anything in the headers to indicate you've hit the limit?

At the very least, this code could be checking the status code and give an appropriate error.

**Comment by edurd** [comment]
@ericjsilva how can I know if I'm violating the Terms of Service?

**Comment by ericjsilva** [comment]
@edurd https://cloud.google.com/terms/service-terms#7-google-cloud-translation-api
